<?php
declare(strict_types=1);

require_once 'db_connect.php';
require_once 'src/entity/User.php';
require_once 'src/entity/Group.php';
require_once 'src/entity/Post.php';
require_once 'src/repository/UserRepo.php';
require_once 'src/repository/GroupRepo.php';
require_once 'src/repository/PostRepo.php';

$userRepo  = new UserRepo($pdo);
$groupRepo = new GroupRepo($pdo);
$postRepo  = new PostRepo($pdo);

$demoEmail = "talel.demo@example.com";

$allUsers = $userRepo->fetchAll();
$userId = null;

foreach ($allUsers as $u) {
    if ($u->getEmail() === $demoEmail) {
        $userId = $u->getId();
    }
}

if (!$userId) {
    $userId = $userRepo->create(12345678, "talel", "Developer", $demoEmail, password_hash("123", PASSWORD_DEFAULT));
    echo "<p style='color: green;'>✅ New user created with ID: $userId</p>";
}

$groups = $groupRepo->fetchAll();
if (empty($groups)) {
    $groupId = $groupRepo->create("PHP & Postgres Masterclass", $userId);
} else {
}

$postRepo->create("Hello world! This post was generated by our Repo pattern.", $userId, $groupId);

$posts = $postRepo->fetchAll();
?>

<!DOCTYPE html>
<html lang="fr">
<head>
    <title>talel Blog Demo</title>
    <style>
        body { font-family: sans-serif; max-width: 800px; margin: 40px auto; line-height: 1.6; }
        .post-card { background: #f9f9f9; border-left: 5px solid #007bff; padding: 15px; margin-bottom: 20px; border-radius: 4px; }
        .post-meta { font-size: 0.8rem; color: #666; }
    </style>
</head>
<body>

    <h1>Welcome to the Blog Demo</h1>
    <hr>

    <h2>Recent Posts</h2>
    <?php if (empty($posts)): ?>
        <p>No posts found.</p>
    <?php else: ?>
        <?php foreach ($posts as $post): ?>
            <?= $post->toHtml() ?>
        <?php endforeach; ?>
    <?php endif; ?>

    <hr>
    <h3>Debug Info (using __toString)</h3>
    <pre>
<?php
    foreach ($posts as $post) {
        echo $post . PHP_EOL;
    }
?>
    </pre>

</body>
</html>
